apiVersion: v1
kind: Template
labels:
  component: fluentd
  logging-infra: fluentd
  provider: openshift
metadata:
  annotations:
    description: Template for logging fluentd deployment.
    tags: infrastructure
  creationTimestamp: null
  labels:
    app: logging-fluentd-template
    logging-infra: fluentd
  name: logging-fluentd-daemonset-template
objects:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      deploymentconfig: fluentd
      provider: openshift
    name: logging-fluentd
  spec:
    selector:
      matchLabels:
        deploymentconfig: fluentd
        provider: openshift
    template:
      metadata:
        labels:
          deploymentconfig: fluentd
          provider: openshift
        name: fluentd
      spec:
        containers:
        - env:
          - name: K8S_HOST_URL
            value: https://kubernetes.default.svc
          image: ${IMAGE_PREFIX}:${IMAGE_VERSION}
          imagePullPolicy: Always
          name: fluentd
          resources:
            limits:
              cpu: 1000m
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/log
            name: varlog
          - mountPath: /var/lib/origin/log/
            name: oselog
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
            readOnly: true
          - mountPath: /etc/fluent/configs.d/user
            name: config
            readOnly: true
          - mountPath: /etc/docker-hostname
            name: dockerhostname
            readOnly: true
        nodeSelector:
          logging-infra-fluentd: "true"
        serviceAccountName: aggregated-logging-fluentd
        volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/origin/log/
          name: oselog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - configMap:
            name: logging-fluentd
          name: config
        - hostPath:
            path: /etc/hostname
          name: dockerhostname
    updateStrategy:
      rollingUpdate:
        minReadySeconds: 600
      type: RollingUpdate
parameters:
- description: The image prefix for the Fluentd image to use
  name: IMAGE_PREFIX
  value: registry.travelsky.com:5000/openshift3/kafka-logging-fluentd
- description: The image version for the Fluentd image to use
  name: IMAGE_VERSION
  value: 3.4.0
